### ISSUE TITLE
Disqualification

### ISSUE THREAD

**Issue by kheneahm-ares** [amazing-username/CSC3610_Triathlon#2]
Kajjumba wants us to implement a constant time that is the the limit for each event.  Since we are doing at least 10+ competitors, there's a chance that one of them will be disqualified.  Anyways, I was thinking that as we're generating a random time for each event, we should have it multiply by 61-65 so that if that it is generated as a number above that constant, they will be disqualified.  Nullifying their results

**Comment by kdeng00** [comment]
True, true. Also, since disqualiication counts for all the forseen events the first instance worthy of disqualification will disqualify said athlete from the other events. If an athlete got disqualified for Swimming then that athlete's data will no longer be timed.

**Comment by kdeng00** [comment]
Gotcha. I changed the time for the generated values. Using the random method from the Math class generates a double that is greater than or equal to 0 but less than 1. Multiplying the value from the random method will return a value that is less than the multiplied value.
Example: 
(Math.random() x 65) can equal to anything including 0 to 65 but not 65.

With that in mind if we are generating times for the events there is a chance that it will generate an absurdly event time like zero or one minute. To prevent this from happening we will add a number to the equation to prevent this, thus widening the shifting the range.
Example:
11 + (Math.random() x 65) can equal to anything from 11 to 76 but not 76.
